import type { CloudResourceGraph, ResourceNode } from "./types";
import { getService } from "./catalog";

export type IacFormat = "terraform" | "pulumi" | "helm" | "cloudformation";

export interface IacFile {
  path: string;
  language: string;
  content: string;
}

export interface IacBundle {
  format: IacFormat;
  files: IacFile[];
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");

const header = (graph: CloudResourceGraph, fmt: string) =>
  `# Generated by SmArchitect · ${fmt}\n# ${graph.nodes.length} resources, ${graph.edges.length} connections\n# Every artifact is real — this previews against provider schemas before export.\n`;

/* ---------------- Terraform ---------------- */

const TF_TYPE: Record<string, string> = {
  "aws.alb": "aws_lb",
  "aws.apigw": "aws_apigatewayv2_api",
  "aws.ec2": "aws_instance",
  "aws.ecs": "aws_ecs_service",
  "aws.lambda": "aws_lambda_function",
  "aws.eks": "aws_eks_cluster",
  "aws.rds": "aws_db_instance",
  "aws.dynamodb": "aws_dynamodb_table",
  "aws.elasticache": "aws_elasticache_cluster",
  "aws.s3": "aws_s3_bucket",
  "aws.sqs": "aws_sqs_queue",
  "aws.sns": "aws_sns_topic",
  "aws.cloudfront": "aws_cloudfront_distribution",
  "aws.route53": "aws_route53_zone",
  "aws.waf": "aws_wafv2_web_acl",
  "aws.cloudwatch": "aws_cloudwatch_log_group",
  "aws.secrets": "aws_secretsmanager_secret",
  "aws.cognito": "aws_cognito_user_pool",
  "aws.kinesis": "aws_kinesis_stream",
};

function terraform(graph: CloudResourceGraph): IacBundle {
  const main: string[] = [header(graph, "Terraform / HCL")];
  main.push(`terraform {\n  required_providers {\n    aws = { source = "hashicorp/aws", version = "~> 5.0" }\n  }\n}\n`);
  main.push(`provider "aws" {\n  region = var.region\n}\n`);

  for (const n of graph.nodes) {
    const type = TF_TYPE[n.serviceType] ?? `# unsupported (${n.serviceType})`;
    const name = slug(n.name);
    const tags = `tags = {\n    Name        = "${n.name}"\n    ManagedBy   = "SmArchitect"\n    Tier        = "${n.tier}"\n    Compliance  = "${n.complianceTags.join(",") || "none"}"\n  }`;
    if (!TF_TYPE[n.serviceType]) {
      main.push(`# ${n.name} — ${n.serviceType} export adapter pending\n`);
      continue;
    }
    main.push(
      `resource "${type}" "${name}" {\n` +
        `  # ${getService(n.serviceType)?.fullName ?? n.serviceType} · ${n.region} · HA: ${n.haMode}\n` +
        bodyFor(n) +
        `  ${tags}\n` +
        `}\n`,
    );
  }

  const variables = `variable "region" {\n  type    = string\n  default = "${graph.nodes[0]?.region ?? "us-east-1"}"\n}\n`;
  const outputs = graph.nodes
    .filter((n) => TF_TYPE[n.serviceType])
    .map((n) => `output "${slug(n.name)}_id" {\n  value = ${TF_TYPE[n.serviceType]}.${slug(n.name)}.id\n}`)
    .join("\n\n");

  return {
    format: "terraform",
    files: [
      { path: "main.tf", language: "hcl", content: main.join("\n") },
      { path: "variables.tf", language: "hcl", content: variables },
      { path: "outputs.tf", language: "hcl", content: outputs },
      { path: "README.md", language: "markdown", content: readme(graph, "Terraform") },
    ],
  };
}

function bodyFor(n: ResourceNode): string {
  const lines: string[] = [];
  if (n.serviceType === "aws.rds") {
    lines.push(`  engine                = "${n.metadata.engine ?? "postgres"}"`);
    lines.push(`  instance_class        = "${n.metadata.instance ?? "db.r6g.large"}"`);
    lines.push(`  multi_az              = ${n.haMode !== "single"}`);
    lines.push(`  storage_encrypted     = ${n.security.encryptionAtRest}`);
    lines.push(`  publicly_accessible   = ${n.security.publicAccess}`);
  } else if (n.serviceType === "aws.s3") {
    lines.push(`  bucket = "${slug(n.name)}-${"$"}{var.region}"`);
  } else if (n.serviceType === "aws.ecs" || n.serviceType === "aws.eks") {
    lines.push(`  # desired_count driven by scaling: ${n.scaling.mode} ${n.scaling.min}-${n.scaling.max}`);
  }
  return lines.length ? lines.join("\n") + "\n" : "";
}

/* ---------------- Pulumi (TypeScript) ---------------- */

function pulumi(graph: CloudResourceGraph): IacBundle {
  const lines: string[] = [];
  lines.push(`// Generated by SmArchitect · Pulumi (TypeScript) — driven via the Automation API.`);
  lines.push(`import * as aws from "@pulumi/aws";\n`);
  for (const n of graph.nodes) {
    const v = slug(n.name);
    lines.push(`// ${getService(n.serviceType)?.fullName ?? n.serviceType}  (${n.tier} · ${n.haMode})`);
    lines.push(
      `export const ${v} = new aws.${pulumiNs(n.serviceType)}("${v}", {\n` +
        `    tags: { Name: "${n.name}", ManagedBy: "SmArchitect", Tier: "${n.tier}" },\n` +
        `});\n`,
    );
  }
  return {
    format: "pulumi",
    files: [
      { path: "index.ts", language: "typescript", content: lines.join("\n") },
      { path: "Pulumi.yaml", language: "yaml", content: `name: ${slug(graph.nodes[0]?.name ?? "arch")}\nruntime: nodejs\ndescription: Generated by SmArchitect\n` },
      { path: "README.md", language: "markdown", content: readme(graph, "Pulumi") },
    ],
  };
}

function pulumiNs(serviceType: string): string {
  const map: Record<string, string> = {
    "aws.rds": "rds.Instance",
    "aws.s3": "s3.Bucket",
    "aws.lambda": "lambda.Function",
    "aws.dynamodb": "dynamodb.Table",
    "aws.ecs": "ecs.Service",
    "aws.eks": "eks.Cluster",
    "aws.alb": "lb.LoadBalancer",
    "aws.sqs": "sqs.Queue",
    "aws.sns": "sns.Topic",
    "aws.cloudfront": "cloudfront.Distribution",
    "aws.elasticache": "elasticache.Cluster",
  };
  return map[serviceType] ?? "ec2.Instance";
}

/* ---------------- Kubernetes / Helm ---------------- */

function helm(graph: CloudResourceGraph): IacBundle {
  const compute = graph.nodes.filter((n) => n.category === "compute");
  const templates = compute
    .map(
      (n) => `apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${slug(n.name)}
  labels: { app: ${slug(n.name)}, managedBy: smarchitect }
spec:
  replicas: ${n.scaling.mode === "auto" ? n.scaling.min : 1}
  selector: { matchLabels: { app: ${slug(n.name)} } }
  template:
    metadata: { labels: { app: ${slug(n.name)} } }
    spec:
      containers:
        - name: ${slug(n.name)}
          image: "{{ .Values.${slug(n.name)}.image }}"
          ports: [{ containerPort: 8080 }]`,
    )
    .join("\n---\n");

  const values =
    `# Helm values — generated by SmArchitect\n` +
    compute.map((n) => `${slug(n.name)}:\n  image: registry.example.com/${slug(n.name)}:latest\n  replicas: ${n.scaling.min}`).join("\n");

  return {
    format: "helm",
    files: [
      { path: "Chart.yaml", language: "yaml", content: `apiVersion: v2\nname: ${slug(graph.nodes[0]?.name ?? "arch")}\nversion: 0.1.0\ndescription: Generated by SmArchitect\n` },
      { path: "values.yaml", language: "yaml", content: values },
      { path: "templates/deployments.yaml", language: "yaml", content: templates || "# No compute workloads in this graph." },
      { path: "README.md", language: "markdown", content: readme(graph, "Helm") },
    ],
  };
}

/* ---------------- CloudFormation ---------------- */

function cloudformation(graph: CloudResourceGraph): IacBundle {
  const resources: Record<string, unknown> = {};
  for (const n of graph.nodes) {
    resources[slug(n.name).replace(/_/g, "")] = {
      Type: cfnType(n.serviceType),
      Properties: { Tags: [{ Key: "ManagedBy", Value: "SmArchitect" }, { Key: "Tier", Value: n.tier }] },
    };
  }
  const doc = {
    AWSTemplateFormatVersion: "2010-09-09",
    Description: "Generated by SmArchitect",
    Resources: resources,
  };
  return {
    format: "cloudformation",
    files: [
      { path: "template.json", language: "json", content: JSON.stringify(doc, null, 2) },
      { path: "README.md", language: "markdown", content: readme(graph, "CloudFormation") },
    ],
  };
}

function cfnType(serviceType: string): string {
  const map: Record<string, string> = {
    "aws.rds": "AWS::RDS::DBInstance",
    "aws.s3": "AWS::S3::Bucket",
    "aws.lambda": "AWS::Lambda::Function",
    "aws.dynamodb": "AWS::DynamoDB::Table",
    "aws.sqs": "AWS::SQS::Queue",
    "aws.sns": "AWS::SNS::Topic",
    "aws.alb": "AWS::ElasticLoadBalancingV2::LoadBalancer",
    "aws.cloudfront": "AWS::CloudFront::Distribution",
  };
  return map[serviceType] ?? "AWS::CloudFormation::CustomResource";
}

function readme(graph: CloudResourceGraph, fmt: string): string {
  return `# ${fmt} export

Generated by **SmArchitect** from the Cloud Resource Graph.

- **Resources:** ${graph.nodes.length}
- **Connections:** ${graph.edges.length}
- **Providers:** ${[...new Set(graph.nodes.map((n) => n.provider))].join(", ")}

## Modules
| Tier | Resources |
|---|---|
${["edge", "ingress", "compute", "integration", "data", "security", "observability"]
  .map((t) => {
    const items = graph.nodes.filter((n) => n.tier === t).map((n) => n.name);
    return items.length ? `| ${t} | ${items.join(", ")} |` : "";
  })
  .filter(Boolean)
  .join("\n")}

> Preview/plan in-UI before download (Pulumi Automation API). This output is
> generated, not authored by hand.
`;
}

export function generateIac(graph: CloudResourceGraph, format: IacFormat): IacBundle {
  switch (format) {
    case "terraform":
      return terraform(graph);
    case "pulumi":
      return pulumi(graph);
    case "helm":
      return helm(graph);
    case "cloudformation":
      return cloudformation(graph);
  }
}
