"""AI buzzword → natural human alternatives (longest phrases first)."""

from __future__ import annotations

# Each entry: phrase (lowercase key) -> list of alternatives; first is default.
AI_WORD_REPLACEMENTS: dict[str, list[str]] = {
    # Multi-word phrases (matched before single words)
    "it's important to note that": ["note that", "keep in mind that"],
    "it is important to note that": ["note that", "keep in mind that"],
    "it is worth noting that": ["note that"],
    "it is worth mentioning that": ["note that"],
    "it should be noted that": ["note that"],
    "it is essential to note that": ["note that"],
    "in today's fast-paced world": ["today"],
    "in today's digital age": ["today"],
    "in today's world": ["today"],
    "in the ever-evolving landscape": ["in this area"],
    "plays a crucial role": ["matters", "is central"],
    "plays a vital role": ["matters", "is central"],
    "plays a key role": ["matters", "is central"],
    "a wide range of": ["many", "several"],
    "a myriad of": ["many"],
    "due to the fact that": ["because"],
    "in order to": ["to"],
    "with regard to": ["about", "on"],
    "in terms of": ["for", "regarding"],
    "at the end of the day": ["ultimately"],
    "when it comes to": ["for", "with"],
    "on the other hand": ["by contrast", "conversely"],
    "as a matter of fact": ["in fact"],
    "in light of": ["given", "considering"],
    "with respect to": ["about", "for"],
    "in the realm of": ["in"],
    "in the context of": ["in", "for"],
    "serves as a testament to": ["shows"],
    "a testament to": ["evidence of"],
    "it's no secret that": [""],
    "needless to say": [""],
    "without further ado": [""],
    "first and foremost": ["first"],
    "last but not least": ["finally"],
    "all things considered": ["overall"],
    "in this day and age": ["today"],
    "cutting-edge": ["recent", "current"],
    "state-of-the-art": ["current", "modern"],
    "best-in-class": ["strong", "leading"],
    "game-changing": ["significant"],
    "ground-breaking": ["notable"],
    "groundbreaking": ["notable"],
    "world-class": ["strong"],
    "next-generation": ["newer"],
    "future-proof": ["durable", "lasting"],
    "human-in-the-loop": ["human-in-the-loop"],  # domain term; keep
    # Single words and short phrases
    "furthermore": ["also", "and"],
    "moreover": ["also", "and"],
    "additionally": ["also"],
    "nevertheless": ["still", "yet"],
    "nonetheless": ["still", "yet"],
    "consequently": ["so", "thus"],
    "accordingly": ["so"],
    "henceforth": ["from then on"],
    "wherein": ["where"],
    "whereby": ["by which"],
    "therein": ["there"],
    "thereof": ["of it"],
    "heretofore": ["until now"],
    "notwithstanding": ["despite"],
    "in conclusion": ["finally", "to close"],
    "to summarize": ["in short"],
    "in summary": ["in short"],
    "to sum up": ["in short"],
    "overall": ["on balance"],
    "delve into": ["examine", "explore"],
    "delving into": ["examining", "exploring"],
    "delve": ["examine", "explore"],
    "delving": ["examining", "exploring"],
    "delves": ["examines", "explores"],
    "leverage": ["use", "apply"],
    "leveraging": ["using", "applying"],
    "leveraged": ["used", "applied"],
    "leverages": ["uses", "applies"],
    "utilize": ["use"],
    "utilizes": ["uses"],
    "utilizing": ["using"],
    "utilized": ["used"],
    "utilization": ["use"],
    "facilitate": ["help", "enable"],
    "facilitates": ["helps", "enables"],
    "facilitating": ["helping", "enabling"],
    "facilitated": ["helped", "enabled"],
    "robust": ["strong", "reliable"],
    "comprehensive": ["full", "complete", "thorough"],
    "holistic": ["whole-system", "integrated"],
    "paradigm": ["model", "approach"],
    "landscape": ["field", "space", "setting"],
    "ecosystem": ["system", "environment"],
    "synergy": ["combined effect"],
    "synergistic": ["combined"],
    "streamline": ["simplify", "speed up"],
    "streamlined": ["simpler", "faster"],
    "streamlining": ["simplifying"],
    "empower": ["let", "enable"],
    "empowers": ["lets", "enables"],
    "empowering": ["enabling"],
    "underscore": ["highlight", "stress"],
    "underscores": ["highlights", "stresses"],
    "underscoring": ["highlighting"],
    "showcase": ["show", "demonstrate"],
    "showcases": ["shows", "demonstrates"],
    "showcasing": ["showing"],
    "nuanced": ["subtle", "fine-grained"],
    "multifaceted": ["varied", "complex"],
    "intricate": ["complex", "detailed"],
    "pivotal": ["central", "key"],
    "paramount": ["primary", "main"],
    "crucial": ["important", "key"],
    "vital": ["important", "key"],
    "essential": ["needed", "required"],
    "fundamental": ["basic", "core"],
    "transformative": ["major", "significant"],
    "innovative": ["new", "novel"],
    "novel": ["new"],
    "seamless": ["smooth", "easy"],
    "seamlessly": ["smoothly", "easily"],
    "meticulous": ["careful", "detailed"],
    "meticulously": ["carefully"],
    "intricately": ["closely"],
    "notably": ["in particular"],
    "importantly": [""],
    "significantly": ["markedly", "clearly"],
    "remarkably": ["clearly"],
    "undeniably": [""],
    "unquestionably": [""],
    "arguably": [""],
    "indeed": [""],
    "certainly": [""],
    "simply put": [""],
    "literally": [""],
    "actually": [""],
    "really": [""],
    "profoundly": ["strongly"],
    "myriad": ["many"],
    "plethora": ["many"],
    "a plethora of": ["many"],
    "plethora of": ["many"],
    "myriad of": ["many"],
    "embark": ["start", "begin"],
    "embarking": ["starting"],
    "embarked": ["started"],
    "navigate": ["handle", "work through"],
    "navigating": ["handling"],
    "navigates": ["handles"],
    "spearhead": ["lead", "drive"],
    # Technical CS/OR terms intentionally omitted: deploy, implementation, optimize, augment, framework
    "enhance": ["improve", "strengthen"],
    "enhancing": ["improving"],
    "enhanced": ["improved"],
    "enhances": ["improves"],
    # implement/deployment/optimize — kept for academic precision
    "methodology": ["method", "approach"],
    "modality": ["mode", "form"],
    "dynamics": ["behavior", "patterns"],
    "interplay": ["interaction"],
    "tapestry": ["mix", "blend"],
    "cornerstone": ["basis", "foundation"],
    "bedrock": ["basis", "foundation"],
    "linchpin": ["key part"],
    "catalyst": ["driver", "trigger"],
    "nexus": ["link", "hub"],
    "underpinning": ["basis", "support"],
    "underpin": ["support", "ground"],
    "underpins": ["supports", "grounds"],
}

# Phrases sorted longest-first for greedy matching.
PHRASES_BY_LENGTH: list[tuple[str, list[str]]] = sorted(
    AI_WORD_REPLACEMENTS.items(),
    key=lambda kv: len(kv[0]),
    reverse=True,
)
