"""IaC plane — emit Terraform from the CRG.

The full platform drives Pulumi via the Automation API for in-UI preview/plan;
this scaffold emits Terraform/HCL as one of the export adapters.
"""
from __future__ import annotations

import re
from .models import CloudResourceGraph

TF_TYPE = {
    "aws.alb": "aws_lb",
    "aws.apigw": "aws_apigatewayv2_api",
    "aws.ecs": "aws_ecs_service",
    "aws.lambda": "aws_lambda_function",
    "aws.eks": "aws_eks_cluster",
    "aws.rds": "aws_db_instance",
    "aws.dynamodb": "aws_dynamodb_table",
    "aws.elasticache": "aws_elasticache_cluster",
    "aws.s3": "aws_s3_bucket",
    "aws.sqs": "aws_sqs_queue",
    "aws.cloudfront": "aws_cloudfront_distribution",
    "aws.route53": "aws_route53_zone",
    "aws.cloudwatch": "aws_cloudwatch_log_group",
    "aws.secrets": "aws_secretsmanager_secret",
}


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", s.lower()).strip("_")


def to_terraform(graph: CloudResourceGraph) -> str:
    out = [
        f"# Generated by SmArchitect · {len(graph.nodes)} resources, {len(graph.edges)} connections",
        'terraform {\n  required_providers {\n    aws = { source = "hashicorp/aws", version = "~> 5.0" }\n  }\n}',
        'provider "aws" {\n  region = var.region\n}',
        'variable "region" {\n  type    = string\n  default = "us-east-1"\n}',
    ]
    for n in graph.nodes:
        tf = TF_TYPE.get(n.serviceType)
        if not tf:
            out.append(f"# {n.name} — {n.serviceType} export adapter pending")
            continue
        body = ""
        if n.serviceType == "aws.rds":
            body = (
                f'  multi_az            = {str(n.haMode != "single").lower()}\n'
                f'  storage_encrypted   = {str(n.security.encryptionAtRest).lower()}\n'
                f'  publicly_accessible = {str(n.security.publicAccess).lower()}\n'
            )
        out.append(
            f'resource "{tf}" "{_slug(n.name)}" {{\n'
            f"  # {n.serviceType} · {n.region} · HA: {n.haMode}\n"
            f"{body}"
            f'  tags = {{ Name = "{n.name}", ManagedBy = "SmArchitect", Tier = "{n.tier}" }}\n'
            f"}}"
        )
    return "\n\n".join(out) + "\n"
